spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sm?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: '1234'  # 注意：密码是数字时，建议用引号包裹
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

# 以下是CORS配置，注释掉的部分
# spring:
#   mvc:
#     cors:
#       allowed-origins: http://localhost:*
#       allowed-methods: GET,POST,PUT,DELETE,OPTIONS
#       allowed-headers: "*"
#       allow-credentials: true
#       max-age: 3600

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

file:
  upload-dir: ./uploads


mybatis:
  mapper-locations: classpath*:mapper/*.xml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
#  packages-to-scan: com.example.demo
  paths-to-match: /api/**
  security:
    - name: BearerAuth
      type: http
      scheme: bearer
      bearerFormat: JWT


jwt:
  secret: 5H6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7A8B9C0D1E2F3G4H5I6J7K8L9M0N1O2P3Q4R5S6T7U8V9W0X1Y2Z3
  expiration: 604800 # 7 days in seconds